-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('Nam', 'Nữ');

-- CreateTable
CREATE TABLE "STUDENTS" (
    "ID" SERIAL NOT NULL,
    "NAME" TEXT NOT NULL,
    "CLASS_ID" INTEGER NOT NULL,

    CONSTRAINT "STUDENTS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "CLASSES" (
    "ID" SERIAL NOT NULL,
    "NAME" TEXT NOT NULL,
    "TEACHER_NAME" TEXT,

    CONSTRAINT "CLASSES_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "STUDENT_PROFILES" (
    "STUDENT_ID" INTEGER NOT NULL,
    "ADDRESS" TEXT,
    "PHONE" TEXT,
    "AGE" INTEGER NOT NULL,
    "GENDER" "Gender",
    "DATE_OF_BIRTH" TIMESTAMP(3),

    CONSTRAINT "STUDENT_PROFILES_pkey" PRIMARY KEY ("STUDENT_ID")
);

-- CreateTable
CREATE TABLE "STUDENT_COURSE" (
    "STUDENT_ID" INTEGER NOT NULL,
    "COURSE_ID" INTEGER NOT NULL,

    CONSTRAINT "STUDENT_COURSE_pkey" PRIMARY KEY ("STUDENT_ID","COURSE_ID")
);

-- CreateTable
CREATE TABLE "COURSES" (
    "ID" SERIAL NOT NULL,
    "TITLE" TEXT NOT NULL,
    "DESCRIPTION" TEXT,

    CONSTRAINT "COURSES_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "STUDENTS" ADD CONSTRAINT "STUDENTS_CLASS_ID_fkey" FOREIGN KEY ("CLASS_ID") REFERENCES "CLASSES"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STUDENT_PROFILES" ADD CONSTRAINT "STUDENT_PROFILES_STUDENT_ID_fkey" FOREIGN KEY ("STUDENT_ID") REFERENCES "STUDENTS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STUDENT_COURSE" ADD CONSTRAINT "STUDENT_COURSE_STUDENT_ID_fkey" FOREIGN KEY ("STUDENT_ID") REFERENCES "STUDENTS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "STUDENT_COURSE" ADD CONSTRAINT "STUDENT_COURSE_COURSE_ID_fkey" FOREIGN KEY ("COURSE_ID") REFERENCES "COURSES"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
